package es.gresybano.gresybano.domain.response

enum class CodeExceptions {

    CONNECT_EXCEPTION,
    UNKNOWN_HOST_EXCEPTION,
    SOCKET_TIME_OUT_EXCEPTION,
    UNKNOWN_NETWORK_EXCEPTION,
    DATABASE_ROOM_ERROR,
    UNKNOWN,
    DATA_NULL_IN_SUCCESSFUL,
    NOT_FIND_DATA_VERSION_CONTROL,

}